package com.paragrein.logistics.enums;

public enum OrderStatus {
    PENDING_ADVANCE_VERIFICATION,
    ASSIGNED_TO_PICKUP,
    PICKUP_ACCEPTED,
    IN_TRANSIT_TO_WAREHOUSE,
    ARRIVED_AT_WAREHOUSE,
    WAREHOUSE_PROCESSING,
    READY_FOR_DISPATCH,
    ASSIGNED_TO_DELIVERY,
    DELIVERY_ACCEPTED,
    REACHED_DESTINATION,
    DELIVERED,
    REJECTED,
    CANCELLED
}
