package com.paragrein.logistics.util;

import com.paragrein.logistics.entity.User;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

public class PdfReportGenerator {

    private final String title;
    private final List<String> headers;
    private final List<List<String>> rows;
    private final User generatedBy;
    private final LocalDate dateFrom;
    private final LocalDate dateTo;

    private final PDType1Font FONT_BOLD = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
    private final PDType1Font FONT_REGULAR = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
    
    private final float MARGIN = 50;
    private float yPosition;

    public PdfReportGenerator(String title, List<String> headers, List<List<String>> rows, User generatedBy, LocalDate dateFrom, LocalDate dateTo) {
        this.title = title;
        this.headers = headers;
        this.rows = rows;
        this.generatedBy = generatedBy;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
    }

    public byte[] generate() throws IOException {
        try (PDDocument document = new PDDocument(); ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            PDPage page = new PDPage(new PDRectangle(PDRectangle.A4.getHeight(), PDRectangle.A4.getWidth()));
            document.addPage(page);
            
            this.yPosition = page.getMediaBox().getHeight() - MARGIN;

            PDPageContentStream contentStream = new PDPageContentStream(document, page);
            
            drawHeader(document, contentStream);
            drawTitle(contentStream, page);
            drawMetadata(contentStream);
            drawTable(contentStream);
            drawFooter(contentStream, page, 1, 1);

            contentStream.close();
            document.save(outputStream);
            return outputStream.toByteArray();
        }
    }

    private void drawHeader(PDDocument document, PDPageContentStream contentStream) throws IOException {
        try (InputStream logoStream = getClass().getResourceAsStream("/static/images/logo.png")) {
            if (logoStream != null) {
                PDImageXObject logo = PDImageXObject.createFromByteArray(document, logoStream.readAllBytes(), "logo");
                contentStream.drawImage(logo, MARGIN, yPosition - 35, 50, 50);
            }
        }
        
        yPosition -= 15;
        writeText(contentStream, "PARAGREIN LOGISTICS", FONT_BOLD, 24, MARGIN + 60, yPosition);
        yPosition -= 20;
        writeText(contentStream, "Logistics Management System", FONT_REGULAR, 14, MARGIN + 60, yPosition);
        yPosition -= 20;
        drawHorizontalLine(contentStream, MARGIN, yPosition, 742);
    }

    private void drawTitle(PDPageContentStream contentStream, PDPage page) throws IOException {
        yPosition -= 30;
        float titleWidth = FONT_BOLD.getStringWidth(title) / 1000 * 18;
        float x = (page.getMediaBox().getWidth() - titleWidth) / 2;
        writeText(contentStream, title, FONT_BOLD, 18, x, yPosition);
        yPosition -= 20;
        drawHorizontalLine(contentStream, MARGIN, yPosition, 742);
    }

    private void drawMetadata(PDPageContentStream contentStream) throws IOException {
        yPosition -= 20;
        writeText(contentStream, "Generated By   : " + generatedBy.getFullName(), FONT_REGULAR, 10, MARGIN, yPosition);
        yPosition -= 15;
        writeText(contentStream, "Generated On   : " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd MMMM yyyy, hh:mm a")), FONT_REGULAR, 10, MARGIN, yPosition);
        yPosition -= 15;

        String period = "All Records";
        if (dateFrom != null && dateTo != null) {
            period = dateFrom.format(DateTimeFormatter.ofPattern("dd MMM yyyy")) + " - " + dateTo.format(DateTimeFormatter.ofPattern("dd MMM yyyy"));
        } else if (dateFrom != null) {
            period = "From " + dateFrom.format(DateTimeFormatter.ofPattern("dd MMM yyyy"));
        } else if (dateTo != null) {
            period = "Until " + dateTo.format(DateTimeFormatter.ofPattern("dd MMM yyyy"));
        }
        
        writeText(contentStream, "Report Period  : " + period, FONT_REGULAR, 10, MARGIN, yPosition);
        yPosition -= 15;
        writeText(contentStream, "Total Records  : " + rows.size(), FONT_REGULAR, 10, MARGIN, yPosition);
        yPosition -= 20;
        drawHorizontalLine(contentStream, MARGIN, yPosition, 742);
    }

    private void drawTable(PDPageContentStream contentStream) throws IOException {
        yPosition -= 20;
        
        float tableWidth = 742;
        int numberOfCols = headers.size();
        float colWidth = tableWidth / numberOfCols;
        float rowHeight = 20f;
        
        // Draw header
        contentStream.setNonStrokingColor(Color.LIGHT_GRAY);
        contentStream.addRect(MARGIN, yPosition, tableWidth, -rowHeight);
        contentStream.fill();
        
        contentStream.setNonStrokingColor(Color.BLACK);
        float textX = MARGIN + 5;
        float textY = yPosition - 15;
        
        for (String header : headers) {
            writeText(contentStream, header, FONT_BOLD, 10, textX, textY);
            textX += colWidth;
        }
        
        yPosition -= rowHeight;
        
        // Draw rows
        boolean zebra = false;
        for (List<String> row : rows) {
            if (zebra) {
                contentStream.setNonStrokingColor(Color.decode("#f0f0f0"));
                contentStream.addRect(MARGIN, yPosition, tableWidth, -rowHeight);
                contentStream.fill();
                contentStream.setNonStrokingColor(Color.BLACK);
            }
            
            textX = MARGIN + 5;
            textY = yPosition - 15;
            
            for (int i = 0; i < row.size(); i++) {
                String text = row.get(i);
                float currentCellWidth = colWidth;

                if (isNumeric(text)) {
                    float textWidth = FONT_REGULAR.getStringWidth(text) / 1000 * 10;
                    float centeredX = textX + (currentCellWidth - textWidth) / 2;
                    writeText(contentStream, text, FONT_REGULAR, 10, centeredX, textY);
                } else {
                    writeText(contentStream, text, FONT_REGULAR, 10, textX, textY);
                }
                textX += colWidth;
            }
            
            yPosition -= rowHeight;
            zebra = !zebra;
        }
    }

    private void drawFooter(PDPageContentStream contentStream, PDPage page, int pageNum, int totalPages) throws IOException {
        float footerY = MARGIN - 30;
        writeText(contentStream, "Generated automatically by the Logistics Management System", FONT_REGULAR, 8, MARGIN, footerY);
        
        String pageNumText = "Page " + pageNum + " of " + totalPages;
        float textWidth = FONT_REGULAR.getStringWidth(pageNumText) / 1000 * 8;
        float x = page.getMediaBox().getWidth() - MARGIN - textWidth;
        writeText(contentStream, pageNumText, FONT_REGULAR, 8, x, footerY);
    }

    private void writeText(PDPageContentStream contentStream, String text, PDType1Font font, float fontSize, float x, float y) throws IOException {
        contentStream.beginText();
        contentStream.setFont(font, fontSize);
        contentStream.newLineAtOffset(x, y);
        contentStream.showText(text);
        contentStream.endText();
    }
    
    private void drawHorizontalLine(PDPageContentStream contentStream, float xStart, float y, float width) throws IOException {
        contentStream.setLineWidth(0.5f);
        contentStream.moveTo(xStart, y);
        contentStream.lineTo(xStart + width, y);
        contentStream.stroke();
    }

    private boolean isNumeric(String str) {
        if (str == null) {
            return false;
        }
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
