package com.paragrein.logistics.util;

import com.paragrein.logistics.dto.DailyReportResponse;
import com.paragrein.logistics.dto.MonthlyReportResponse;
import com.paragrein.logistics.dto.RevenueReportResponse;
import com.paragrein.logistics.entity.User;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.List;
import java.util.Locale;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

public class PdfReportGenerator {

    private final String title;
    private final List<String> headers;
    private final List<List<String>> rows;
    private final User generatedBy;
    private final LocalDate dateFrom;
    private final LocalDate dateTo;

    public PdfReportGenerator(String title, List<String> headers, List<List<String>> rows, User generatedBy,
            LocalDate dateFrom, LocalDate dateTo) {
        this.title = title;
        this.headers = headers;
        this.rows = rows;
        this.generatedBy = generatedBy;
        this.dateFrom = dateFrom;
        this.dateTo = dateTo;
    }

    public byte[] generate() throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                float margin = 50;
                float yStart = page.getMediaBox().getHeight() - margin;
                float tableWidth = page.getMediaBox().getWidth() - 2 * margin;
                float yPosition = yStart;

                // Header
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 16);
                contentStream.beginText();
                contentStream.newLineAtOffset(margin, yPosition);
                contentStream.showText(title);
                contentStream.endText();
                yPosition -= 20;

                // Sub-header
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 8);
                String generatedAt = "Generated at: "
                        + LocalDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM));
                String generatedBy = "Generated by: " + this.generatedBy.getFullName();
                contentStream.beginText();
                contentStream.newLineAtOffset(margin, yPosition);
                contentStream.showText(generatedAt + " | " + generatedBy);
                contentStream.endText();
                yPosition -= 15;

                if (dateFrom != null && dateTo != null) {
                    String dateRange = "Date Range: " + dateFrom.format(DateTimeFormatter.ISO_LOCAL_DATE) + " to "
                            + dateTo.format(DateTimeFormatter.ISO_LOCAL_DATE);
                    contentStream.beginText();
                    contentStream.newLineAtOffset(margin, yPosition);
                    contentStream.showText(dateRange);
                    contentStream.endText();
                    yPosition -= 20;
                }

                // Table
                drawTable(contentStream, margin, yPosition, tableWidth, headers, rows);
            }

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            document.save(baos);
            return baos.toByteArray();
        }
    }

    private void drawTable(PDPageContentStream contentStream, float x, float y, float tableWidth, List<String> headers,
            List<List<String>> rows) throws IOException {
        int numCols = headers.size();
        float rowHeight = 20f;
        float[] colWidths = new float[numCols];
        for (int i = 0; i < numCols; i++) {
            colWidths[i] = tableWidth / numCols;
        }

        // Draw header
        contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 10);
        float nextX = x;
        for (int i = 0; i < numCols; i++) {
            contentStream.beginText();
            contentStream.newLineAtOffset(nextX + 5, y - 15);
            contentStream.showText(headers.get(i));
            contentStream.endText();
            nextX += colWidths[i];
        }
        drawTableRow(contentStream, x, y, tableWidth, rowHeight);
        float nextY = y - rowHeight;

        // Draw rows
        contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 9);
        for (List<String> row : rows) {
            nextX = x;
            for (int i = 0; i < numCols; i++) {
                contentStream.beginText();
                contentStream.newLineAtOffset(nextX + 5, nextY - 15);
                contentStream.showText(row.get(i) != null ? row.get(i) : "");
                contentStream.endText();
                nextX += colWidths[i];
            }
            drawTableRow(contentStream, x, nextY, tableWidth, rowHeight);
            nextY -= rowHeight;
        }
    }

    private void drawTableRow(PDPageContentStream contentStream, float x, float y, float width, float height)
            throws IOException {
        contentStream.setLineWidth(0.5f);
        contentStream.moveTo(x, y);
        contentStream.lineTo(x + width, y);
        contentStream.stroke();
    }

    public static byte[] generateFinancialSummary(String title, RevenueReportResponse data, User user, LocalDate from,
            LocalDate to) throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                float y = writeHeader(contentStream, title, user, from, to);
                writeSummaryLine(contentStream, "Advance Received:", formatCurrency(data.getTotalAdvance()), y -= 30);
                writeSummaryLine(contentStream, "Balance Collected:", formatCurrency(data.getTotalBalance()), y -= 30);
                writeSummaryLine(contentStream, "Total Revenue:", formatCurrency(data.getTotalRevenue()), y -= 30);
            }
            return saveDocument(document);
        }
    }

    public static byte[] generateMonthlySummary(String title, MonthlyReportResponse data, User user, YearMonth month)
            throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                float y = writeHeader(contentStream,
                        title + " for " + month.format(DateTimeFormatter.ofPattern("MMMM yyyy")), user, null, null);
                y -= 20;
                writeSummaryLine(contentStream, "Total Orders:", String.valueOf(data.getSummary().getTotalOrders()),
                        y -= 30);
                writeSummaryLine(contentStream, "Delivered:", String.valueOf(data.getSummary().getDeliveredOrders()),
                        y -= 20);
                writeSummaryLine(contentStream, "In Warehouse:", String.valueOf(data.getSummary().getWarehouseOrders()),
                        y -= 20);
                writeSummaryLine(contentStream, "Rejected/Cancelled:",
                        String.valueOf(data.getSummary().getRejectedOrders()), y -= 20);
                y -= 20;
                writeSummaryLine(contentStream, "Orders Created This Month:", String.valueOf(data.getOrdersCreated()),
                        y -= 30);
                writeSummaryLine(contentStream, "Orders Delivered This Month:",
                        String.valueOf(data.getOrdersDelivered()), y -= 20);
                writeSummaryLine(contentStream, "Revenue Collected This Month:",
                        formatCurrency(data.getRevenueCollected()), y -= 20);
            }
            return saveDocument(document);
        }
    }

    private static float writeHeader(PDPageContentStream stream, String title, User user, LocalDate from, LocalDate to)
            throws IOException {
        float margin = 50;
        float y = PDRectangle.A4.getHeight() - margin;

        stream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 16);
        stream.beginText();
        stream.newLineAtOffset(margin, y);
        stream.showText(title);
        stream.endText();
        y -= 20;

        stream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 8);
        String generated = "Generated at: "
                + LocalDateTime.now().format(DateTimeFormatter.ofLocalizedDateTime(FormatStyle.MEDIUM)) + " by: "
                + user.getFullName();
        stream.beginText();
        stream.newLineAtOffset(margin, y);
        stream.showText(generated);
        stream.endText();
        y -= 15;

        if (from != null && to != null) {
            String range = "Date Range: " + from.format(DateTimeFormatter.ISO_LOCAL_DATE) + " to "
                    + to.format(DateTimeFormatter.ISO_LOCAL_DATE);
            stream.beginText();
            stream.newLineAtOffset(margin, y);
            stream.showText(range);
            stream.endText();
            y -= 20;
        }
        return y;
    }

    private static void writeSummaryLine(PDPageContentStream stream, String label, String value, float y)
            throws IOException {
        stream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
        stream.beginText();
        stream.newLineAtOffset(60, y);
        stream.showText(label);
        stream.endText();

        stream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 12);
        stream.beginText();
        stream.newLineAtOffset(250, y);
        stream.showText(value);
        stream.endText();
    }

    private static byte[] saveDocument(PDDocument document) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        document.save(baos);
        return baos.toByteArray();
    }

    private static String formatCurrency(BigDecimal value) {
        if (value == null)
            return "Rs. 0.00";
        NumberFormat currencyInstance = NumberFormat.getCurrencyInstance(new Locale("en", "LK"));
        currencyInstance.setCurrency(java.util.Currency.getInstance("LKR"));
        return currencyInstance.format(value);
    }
}